version: 1
gui: './web-gui'

modules:
  strategies:
    dir: '/home/sebu/exp/strattest'  
    strattest:
      dir: './strattest'  

  brokers:
    dir: '/home/sebu/exp/brokers'
    alpaca:
      dir: './alpaca'
